# Project information
site_name: 'Venngage'
site_description: 'Venngage Developer Documentation and Coding Styleguide'
site_author: 'Venngage'
site_url: 'https://enicol.github.io/venngage-styleguide/'
# site_favicon: 'images/favicon.ico'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/enicol/venngage-styleguide'

# Copyright
copyright: 'Copyright &copy; 2018 Venngage'

# Documentation and theme
theme:
  name: 'material'

# Options
extra:
  logo: 'images/venngage-logo.svg'
  palette:
    primary: 'indigo'
    accent: 'teal'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  language: en
  feature:
    tabs: true
  favicon: 'images/favicon.ico'
  social:
    - type: 'github'
      link: 'https://github.com/Venngage'
    - type: 'twitter'
      link: 'https://twitter.com/Venngage'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/venngage'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.critic

# Documentation structure
pages:
-  Home: 'index.md'
-  Internationalization:
    - 'Introduction': 'i18n/introduction.md'
    - 'i18n with Javascript': 'i18n/javascript.md'
    - 'i18n with PHP': 'i18n/php.md'
-  Javascript:
    - 'Basic Coding Standard': 'js/javascript.md'
    - 'React Styleguide': 'js/react.md'
    - 'CSS in Javascript': 'js/css-js.md'
-  PHP:
    - 'Basic Coding Standard': 'php/php-standard.md'
    - 'Coding Styleguide': 'php/php-styleguide.md'
    - 'Logger Interface': 'php/php-interface.md'
    - 'Autoloader': 'php/php-autoloader.md'
    - 'Cache': 'php/php-cache.md'
    - 'HTTP Messages': 'php/php-http-messages.md'
-  Dev Support: 'support/dev-support.md'
- Licenses: 'about/license.md'
